Integrating mesh module
FHOOEAIST/imaging pull request #21
Opened 2021-02-17 08:17 UTC by cpraschl

Closes 5

2021-02-18 13:29 UTC, pointan requested changes

2021-02-18 13:29 UTC, pointan commented on mesh/src/main/java/science/aist/imaging/service/mesh/triangulation/delaunay/AbstractConstrainedDelaunayTriangulation.java
> +     * <p></p>Force the integrity of the constraints used to compute the delaunay triangulation:</p>
The p-tag is closing here too soon. This could possibly lead into a javadoc error.

2021-02-18 13:29 UTC, pointan commented on mesh/src/test/java/science/aist/imaging/service/mesh/storage/stl/StlTest.java
> +        Assert.assertTrue(read.isPresent());
I would move the asserts to then `// then` section, otherwise it is somehow weird, to have a then block where not all assertions are in.

2021-02-18 13:29 UTC, pointan commented on src/site/markdown/changelog.md
> +## Version 1.1.0
I will add this here, as git does not show the heading above ... 
It should be Version 1.2.0

2021-02-18 13:36 UTC, pointan approved these changes

2021-03-24 15:15 UTC, 2er0 approved these changes

2021-03-29 13:37 UTC, merged